/* JavaScript file Generated by
 * Creativyst(tm) CSV converter
 *   (www.creativyst.com)
 * 
 * (C) Copyright 2002-2003, Creativyst, Inc.
 * 
 * Permission is hereby granted to use,
 * distribute, and change this file for any
 * reason, provided this entire comment remains
 * intact with the work.
 * 
 *
*/

/*JSCPragma:StartCompress
*/

var lsz = 192;

var FocalLengthmm = Array([lsz]);
var FOVindegrees = Array([lsz]);

FocalLengthmm[0] = "10";
FOVindegrees[0] = "130";

FocalLengthmm[1] = "11";
FOVindegrees[1] = "126";

FocalLengthmm[2] = "12";
FOVindegrees[2] = "122";

FocalLengthmm[3] = "13";
FOVindegrees[3] = "118";

FocalLengthmm[4] = "14";
FOVindegrees[4] = "114";

FocalLengthmm[5] = "15";
FOVindegrees[5] = "110";

FocalLengthmm[6] = "16";
FOVindegrees[6] = "107";

FocalLengthmm[7] = "17";
FOVindegrees[7] = "104";

FocalLengthmm[8] = "18";
FOVindegrees[8] = "100";

FocalLengthmm[9] = "19";
FOVindegrees[9] = "97";

FocalLengthmm[10] = "20";
FOVindegrees[10] = "94";

FocalLengthmm[11] = "21";
FOVindegrees[11] = "92";

FocalLengthmm[12] = "22";
FOVindegrees[12] = "89";

FocalLengthmm[13] = "23";
FOVindegrees[13] = "86";

FocalLengthmm[14] = "24";
FOVindegrees[14] = "84";

FocalLengthmm[15] = "25";
FOVindegrees[15] = "82";

FocalLengthmm[16] = "26";
FOVindegrees[16] = "79";

FocalLengthmm[17] = "27";
FOVindegrees[17] = "77";

FocalLengthmm[18] = "28";
FOVindegrees[18] = "75";

FocalLengthmm[19] = "29";
FOVindegrees[19] = "73";

FocalLengthmm[20] = "30";
FOVindegrees[20] = "71";

FocalLengthmm[21] = "31";
FOVindegrees[21] = "70";

FocalLengthmm[22] = "32";
FOVindegrees[22] = "68";

FocalLengthmm[23] = "33";
FOVindegrees[23] = "66";

FocalLengthmm[24] = "34";
FOVindegrees[24] = "65";

FocalLengthmm[25] = "35";
FOVindegrees[25] = "63";

FocalLengthmm[26] = "36";
FOVindegrees[26] = "62";

FocalLengthmm[27] = "37";
FOVindegrees[27] = "61";

FocalLengthmm[28] = "38";
FOVindegrees[28] = "59";

FocalLengthmm[29] = "39";
FOVindegrees[29] = "58";

FocalLengthmm[30] = "40";
FOVindegrees[30] = "57";

FocalLengthmm[31] = "41";
FOVindegrees[31] = "56";

FocalLengthmm[32] = "42";
FOVindegrees[32] = "55";

FocalLengthmm[33] = "43";
FOVindegrees[33] = "53";

FocalLengthmm[34] = "44";
FOVindegrees[34] = "52";

FocalLengthmm[35] = "45";
FOVindegrees[35] = "51";

FocalLengthmm[36] = "46";
FOVindegrees[36] = "50";

FocalLengthmm[37] = "47";
FOVindegrees[37] = "49";

FocalLengthmm[38] = "48";
FOVindegrees[38] = "48";

FocalLengthmm[39] = "49";
FOVindegrees[39] = "47";

FocalLengthmm[40] = "50";
FOVindegrees[40] = "46";

FocalLengthmm[41] = "51";
FOVindegrees[41] = "46";

FocalLengthmm[42] = "52";
FOVindegrees[42] = "45";

FocalLengthmm[43] = "53";
FOVindegrees[43] = "44";

FocalLengthmm[44] = "54";
FOVindegrees[44] = "44";

FocalLengthmm[45] = "55";
FOVindegrees[45] = "43";

FocalLengthmm[46] = "56";
FOVindegrees[46] = "42";

FocalLengthmm[47] = "57";
FOVindegrees[47] = "42";

FocalLengthmm[48] = "58";
FOVindegrees[48] = "41";

FocalLengthmm[49] = "59";
FOVindegrees[49] = "40";

FocalLengthmm[50] = "60";
FOVindegrees[50] = "40";

FocalLengthmm[51] = "61";
FOVindegrees[51] = "39";

FocalLengthmm[52] = "62";
FOVindegrees[52] = "38";

FocalLengthmm[53] = "63";
FOVindegrees[53] = "38";

FocalLengthmm[54] = "64";
FOVindegrees[54] = "37";

FocalLengthmm[55] = "65";
FOVindegrees[55] = "37";

FocalLengthmm[56] = "66";
FOVindegrees[56] = "36";

FocalLengthmm[57] = "67";
FOVindegrees[57] = "36";

FocalLengthmm[58] = "68";
FOVindegrees[58] = "35";

FocalLengthmm[59] = "69";
FOVindegrees[59] = "35";

FocalLengthmm[60] = "70";
FOVindegrees[60] = "34";

FocalLengthmm[61] = "71";
FOVindegrees[61] = "34";

FocalLengthmm[62] = "72";
FOVindegrees[62] = "33";

FocalLengthmm[63] = "73";
FOVindegrees[63] = "33";

FocalLengthmm[64] = "74";
FOVindegrees[64] = "32";

FocalLengthmm[65] = "75";
FOVindegrees[65] = "32";

FocalLengthmm[66] = "76";
FOVindegrees[66] = "32";

FocalLengthmm[67] = "77";
FOVindegrees[67] = "31";

FocalLengthmm[68] = "78";
FOVindegrees[68] = "31";

FocalLengthmm[69] = "79";
FOVindegrees[69] = "31";

FocalLengthmm[70] = "80";
FOVindegrees[70] = "30";

FocalLengthmm[71] = "81";
FOVindegrees[71] = "30";

FocalLengthmm[72] = "82";
FOVindegrees[72] = "30";

FocalLengthmm[73] = "83";
FOVindegrees[73] = "29";

FocalLengthmm[74] = "84";
FOVindegrees[74] = "29";

FocalLengthmm[75] = "85";
FOVindegrees[75] = "28";

FocalLengthmm[76] = "86";
FOVindegrees[76] = "28";

FocalLengthmm[77] = "87";
FOVindegrees[77] = "28";

FocalLengthmm[78] = "88";
FOVindegrees[78] = "28";

FocalLengthmm[79] = "89";
FOVindegrees[79] = "27";

FocalLengthmm[80] = "90";
FOVindegrees[80] = "27";

FocalLengthmm[81] = "91";
FOVindegrees[81] = "27";

FocalLengthmm[82] = "92";
FOVindegrees[82] = "26";

FocalLengthmm[83] = "93";
FOVindegrees[83] = "26";

FocalLengthmm[84] = "94";
FOVindegrees[84] = "26";

FocalLengthmm[85] = "95";
FOVindegrees[85] = "26";

FocalLengthmm[86] = "96";
FOVindegrees[86] = "25";

FocalLengthmm[87] = "97";
FOVindegrees[87] = "25";

FocalLengthmm[88] = "98";
FOVindegrees[88] = "25";

FocalLengthmm[89] = "99";
FOVindegrees[89] = "25";

FocalLengthmm[90] = "100";
FOVindegrees[90] = "24";

FocalLengthmm[91] = "101";
FOVindegrees[91] = "24";

FocalLengthmm[92] = "102";
FOVindegrees[92] = "24";

FocalLengthmm[93] = "103";
FOVindegrees[93] = "24";

FocalLengthmm[94] = "104";
FOVindegrees[94] = "23";

FocalLengthmm[95] = "105";
FOVindegrees[95] = "23";

FocalLengthmm[96] = "106";
FOVindegrees[96] = "23";

FocalLengthmm[97] = "107";
FOVindegrees[97] = "23";

FocalLengthmm[98] = "108";
FOVindegrees[98] = "22";

FocalLengthmm[99] = "109";
FOVindegrees[99] = "22";

FocalLengthmm[100] = "110";
FOVindegrees[100] = "22";

FocalLengthmm[101] = "111";
FOVindegrees[101] = "22";

FocalLengthmm[102] = "112";
FOVindegrees[102] = "22";

FocalLengthmm[103] = "113";
FOVindegrees[103] = "21";

FocalLengthmm[104] = "114";
FOVindegrees[104] = "21";

FocalLengthmm[105] = "115";
FOVindegrees[105] = "21";

FocalLengthmm[106] = "116";
FOVindegrees[106] = "21";

FocalLengthmm[107] = "117";
FOVindegrees[107] = "21";

FocalLengthmm[108] = "118";
FOVindegrees[108] = "21";

FocalLengthmm[109] = "119";
FOVindegrees[109] = "20";

FocalLengthmm[110] = "120";
FOVindegrees[110] = "20";

FocalLengthmm[111] = "121";
FOVindegrees[111] = "20";

FocalLengthmm[112] = "122";
FOVindegrees[112] = "20";

FocalLengthmm[113] = "123";
FOVindegrees[113] = "20";

FocalLengthmm[114] = "124";
FOVindegrees[114] = "20";

FocalLengthmm[115] = "125";
FOVindegrees[115] = "19";

FocalLengthmm[116] = "126";
FOVindegrees[116] = "19";

FocalLengthmm[117] = "127";
FOVindegrees[117] = "19";

FocalLengthmm[118] = "128";
FOVindegrees[118] = "19";

FocalLengthmm[119] = "129";
FOVindegrees[119] = "19";

FocalLengthmm[120] = "130";
FOVindegrees[120] = "19";

FocalLengthmm[121] = "131";
FOVindegrees[121] = "19";

FocalLengthmm[122] = "132";
FOVindegrees[122] = "19";

FocalLengthmm[123] = "133";
FOVindegrees[123] = "18";

FocalLengthmm[124] = "134";
FOVindegrees[124] = "18";

FocalLengthmm[125] = "135";
FOVindegrees[125] = "18";

FocalLengthmm[126] = "136";
FOVindegrees[126] = "18";

FocalLengthmm[127] = "137";
FOVindegrees[127] = "18";

FocalLengthmm[128] = "138";
FOVindegrees[128] = "18";

FocalLengthmm[129] = "139";
FOVindegrees[129] = "18";

FocalLengthmm[130] = "140";
FOVindegrees[130] = "18";

FocalLengthmm[131] = "141";
FOVindegrees[131] = "17";

FocalLengthmm[132] = "142";
FOVindegrees[132] = "17";

FocalLengthmm[133] = "143";
FOVindegrees[133] = "17";

FocalLengthmm[134] = "144";
FOVindegrees[134] = "17";

FocalLengthmm[135] = "145";
FOVindegrees[135] = "17";

FocalLengthmm[136] = "146";
FOVindegrees[136] = "17";

FocalLengthmm[137] = "147";
FOVindegrees[137] = "17";

FocalLengthmm[138] = "148";
FOVindegrees[138] = "17";

FocalLengthmm[139] = "149";
FOVindegrees[139] = "16";

FocalLengthmm[140] = "150";
FOVindegrees[140] = "16";

FocalLengthmm[141] = "151";
FOVindegrees[141] = "16";

FocalLengthmm[142] = "152";
FOVindegrees[142] = "16";

FocalLengthmm[143] = "153";
FOVindegrees[143] = "16";

FocalLengthmm[144] = "154";
FOVindegrees[144] = "16";

FocalLengthmm[145] = "155";
FOVindegrees[145] = "16";

FocalLengthmm[146] = "156";
FOVindegrees[146] = "16";

FocalLengthmm[147] = "157";
FOVindegrees[147] = "16";

FocalLengthmm[148] = "158";
FOVindegrees[148] = "15";

FocalLengthmm[149] = "159";
FOVindegrees[149] = "15";

FocalLengthmm[150] = "160";
FOVindegrees[150] = "15";

FocalLengthmm[151] = "161";
FOVindegrees[151] = "15";

FocalLengthmm[152] = "162";
FOVindegrees[152] = "15";

FocalLengthmm[153] = "163";
FOVindegrees[153] = "15";

FocalLengthmm[154] = "164";
FOVindegrees[154] = "15";

FocalLengthmm[155] = "165";
FOVindegrees[155] = "15";

FocalLengthmm[156] = "166";
FOVindegrees[156] = "15";

FocalLengthmm[157] = "167";
FOVindegrees[157] = "15";

FocalLengthmm[158] = "168";
FOVindegrees[158] = "15";

FocalLengthmm[159] = "169";
FOVindegrees[159] = "15";

FocalLengthmm[160] = "170";
FOVindegrees[160] = "14";

FocalLengthmm[161] = "171";
FOVindegrees[161] = "14";

FocalLengthmm[162] = "172";
FOVindegrees[162] = "14";

FocalLengthmm[163] = "173";
FOVindegrees[163] = "14";

FocalLengthmm[164] = "174";
FOVindegrees[164] = "14";

FocalLengthmm[165] = "175";
FOVindegrees[165] = "14";

FocalLengthmm[166] = "176";
FOVindegrees[166] = "14";

FocalLengthmm[167] = "177";
FOVindegrees[167] = "14";

FocalLengthmm[168] = "178";
FOVindegrees[168] = "14";

FocalLengthmm[169] = "179";
FOVindegrees[169] = "14";

FocalLengthmm[170] = "180";
FOVindegrees[170] = "14";

FocalLengthmm[171] = "181";
FOVindegrees[171] = "14";

FocalLengthmm[172] = "182";
FOVindegrees[172] = "14";

FocalLengthmm[173] = "183";
FOVindegrees[173] = "13";

FocalLengthmm[174] = "184";
FOVindegrees[174] = "13";

FocalLengthmm[175] = "185";
FOVindegrees[175] = "13";

FocalLengthmm[176] = "186";
FOVindegrees[176] = "13";

FocalLengthmm[177] = "187";
FOVindegrees[177] = "13";

FocalLengthmm[178] = "188";
FOVindegrees[178] = "13";

FocalLengthmm[179] = "189";
FOVindegrees[179] = "13";

FocalLengthmm[180] = "190";
FOVindegrees[180] = "13";

FocalLengthmm[181] = "191";
FOVindegrees[181] = "13";

FocalLengthmm[182] = "192";
FOVindegrees[182] = "13";

FocalLengthmm[183] = "193";
FOVindegrees[183] = "13";

FocalLengthmm[184] = "194";
FOVindegrees[184] = "13";

FocalLengthmm[185] = "195";
FOVindegrees[185] = "13";

FocalLengthmm[186] = "196";
FOVindegrees[186] = "13";

FocalLengthmm[187] = "197";
FOVindegrees[187] = "12";

FocalLengthmm[188] = "198";
FOVindegrees[188] = "12";

FocalLengthmm[189] = "199";
FOVindegrees[189] = "12";

FocalLengthmm[190] = "200";
FOVindegrees[190] = "12";


